CREATE DATABASE  IF NOT EXISTS `bd_scott`;
USE `bd_scott`;

DROP TABLE IF EXISTS `dept`;
CREATE TABLE `dept` (
  `DEPTNO` int NOT NULL,
  `DNAME` varchar(45) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci NOT NULL,
  `LOC` varchar(45) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL,
  PRIMARY KEY (`DEPTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_spanish2_ci;

LOCK TABLES `dept` WRITE;
INSERT INTO `dept` VALUES (10,'VENTAS','MADRID'),(20,'PRODUCCION','BARCELONA'),(30,'CENTRAL','MADRID');
UNLOCK TABLES;
